name: Run Automation Tests on Windows

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome (Optional)
        run: choco install googlechrome --no-progress

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          cd expense_automation
          python all_tests.py

      - name: Upload HTML Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-reports
          path: expense_automation/reports/*.html

      - name: List PNG files
        if: always()
        run: |
          echo "Searching for screenshots:"
          find . -name '*.png' || echo "No PNG files found" 

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-failures
          path: '**/screenshots/'


